export const FETCHMEMBERS = 'FETCHMEMBERS';
export const ADDMEMBER = 'ADDMEMBER';
export const SETCURRENTMEMBER = 'SETCURRENTMEMBER';
export const CLEARCURRENTMEMBER = 'CLEARCURRENTMEMBER';
export const UPDATEMEMBER = 'UPDATEMEMBER';
export const DELETEMEMBER = 'DELETEMEMBER';