export const FETCHTRAINERS = "FETCHTRAINERS";
export const SETERROR = "SETERROR";
export const ADDTRAINER = "ADDTRAINER";
export const SETCURRENTTRAINER = "SETCURRENTTRAINER";
export const CLEARCURRENTTRAINER = "CLEARCURRENTTRAINER";
export const DELETETRAINER = "DELETETRAINER";
export const UPDATETRAINER = "UPDATETRAINER";
